<!-- FOOTER -->
  <footer class="container conffoter">
    <p class="float-end"><a href="#">Back to top</a></p>
    
    <p>
    <svg width="100px" height="70px" 
    src=<?php include ASSET_DIR . "/images/logo_kingdom_horiz_invertido.svg"; ?> ></svg> 
    &copy; 2022 Kingdom Ltda &middot; <a href="README.md">Terms</a>
    </p>
  </footer>

    <script src="./assets/dist/js/bootstrap.bundle.min.js"></script>