  <header class="d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-3 mb-4 border-bottom">
      <a href="index.php" class="d-flex align-items-center col-md-3 mb-2 mb-md-0 text-dark text-decoration-none">
        <svg width="180px" src=<?php include "./assets/images/logo_kingdom_horiz.svg"; ?></svg>
      </a>

      <ul class="nav col-12 col-md-auto mb-2 justify-content-center mb-md-0">
        <li><a href="index.php" class="nav-link px-2 link-secondary">Home</a></li>
        <li><a href="#" class="nav-link px-2 link-dark">Pesquisar</a></li>
        <li><a href="#" class="nav-link px-2 link-dark">Relatórios</a></li>

        <li><a href="#" class="nav-link px-2 link-dark">Admin</a></li>
      </ul>

      <div class="col-md-3 text-end">
      <a href="./login.php">
        <button type="button" class="btn btn-outline-primary me-2">Entrar</button></a>
        <a href="signup.php"> 
        <button type="button" class="btn btn-primary">Inscreva-se</button></a>
      </div>
    </header>
